version: "3"
services:
    tld:
        build: emoji/.
        networks:
            emojinet:
                ipv4_address: 10.0.0.53
    sld:
        build: smile.emoji/.
        networks:
            emojinet:
                ipv4_address: 10.0.1.53
networks:
    emojinet:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/16
                  gateway: 10.0.0.1
